name: fl_localization
description: A Rich Localiation Service In Flutter.
version: 0.0.3
repository: https://github.com/mohammadne/Flutter-Packages/tree/master/fl_localization
issue_tracker: https://github.com/mohammadne/Flutter-Packages/issues/
homepage: https://github.com/mohammadne/Flutter-Packages/
documentation:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State manegment
  flutter_bloc: ^6.0.1

  # State Persistance
  hydrated_bloc: ^6.0.1

  # Data Classes 
  freezed_annotation: ^0.11.0+1

  # Annotations
  meta: ^1.2.2

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.4.0
  build_runner: ^1.10.2
  freezed: ^0.11.5
  flutter_test:
    sdk: flutter

flutter:
