name: fl_localization
description: A Rich Localiation Service In Flutter.
version: 0.1.1
repository: https://github.com/mohammadne/Flutter-Packages/tree/master/fl_localization
issue_tracker: https://github.com/mohammadne/Flutter-Packages/issues/
homepage: https://github.com/mohammadne/Flutter-Packages/
documentation:

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data Classes 
  freezed_annotation: ^0.11.0+1

  rxdart: ^0.24.1

  # DB and Persistant
  hive_flutter: ^0.3.1
  hive: ^1.4.4

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.4.1
  build_runner: ^1.10.1
  freezed: ^0.11.6
  flutter_test:
    sdk: flutter

flutter:
