name: fl_localization
description: A Rich Localiation Service In Flutter.
version: 0.0.3
repository: https://github.com/mohammadne/Flutter-Packages/tree/master/fl_localization
issue_tracker:
homepage:
documentation:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State manegment
  flutter_bloc: ^4.0.1
  hydrated_bloc: ^4.1.1

  # Data Classes 
  freezed_annotation: ^0.11.0

  # Annotations
  meta: ^1.1.8

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  freezed: ^0.11.2
  flutter_test:
    sdk: flutter

flutter:
