name: fl_theme
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/mohammadne/Flutter-Packages/tree/master/fl_theme
issue_tracker: https://github.com/mohammadne/Flutter-Packages/issues/
homepage: https://github.com/mohammadne/Flutter-Packages/
documentation: null

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Annotations
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0
  
  # Reactive programming
  rxdart: ^0.24.1

  # DB and Persistant
  hive_flutter: ^0.3.1
  hive: ^1.4.4

dev_dependencies:
  json_serializable: ^3.5.0
  hive_generator: ^0.7.2+1
  build_runner: ^1.10.1
  freezed: ^0.11.6
  flutter_test:
    sdk: flutter

flutter: null

