name: fl_audio
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Reactive Stuffs
  rxdart: ^0.24.1

  # Anotations
  freezed_annotation: ^0.11.0

  # Audio Player
  audio_service: ^0.11.2
  just_audio: ^0.2.2

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2
  freezed: ^0.11.2

flutter: