name: fl_audio
description: A concrete implementation of audio_service package 
version: 0.0.2
repository: https://github.com/mohammadne/Flutter-Packages/tree/master/fl_audio
issue_tracker: https://github.com/mohammadne/Flutter-Packages/issues/
homepage: https://github.com/mohammadne/Flutter-Packages/
documentation:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Reactive Stuffs
  rxdart: ^0.24.1

  # DB Stuffs
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  # Anotations
  freezed_annotation: ^0.11.0

  path_provider: ^1.6.11

  # Audio Player
  audio_service: ^0.11.2
  just_audio: ^0.2.2

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2
  freezed: ^0.11.2

flutter: