name: fl_audio
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Reactive Stuffs
  rxdart: ^0.24.1

  # Audio Player
  audio_service: ^0.11.2
  just_audio: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: