name: fl_api
description: A new Flutter package project.
version: 0.1.1
repository: https://github.com/mohammadne/Flutter-Packages/tree/master/fl_api
issue_tracker: https://github.com/mohammadne/Flutter-Packages/issues/
homepage: https://github.com/mohammadne/Flutter-Packages/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.12.0
  dartz: ^0.9.2
  dio: ^3.0.10

dev_dependencies:
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  freezed: ^0.12.2
  flutter_test:
    sdk: flutter

flutter:
