name: fl_switch
description: A library to draw fantastic Switches with nice animations in Flutter
version: 0.1.0
repository: https://github.com/mohammadne/Flutter-Packages/tree/master/fl_switch
issue_tracker: https://github.com/mohammadne/Flutter-Packages/issues/
homepage: https://github.com/mohammadne/Flutter-Packages/
documentation:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

